### ISSUE TITLE
Fails with Config-MethodProxy-0.02

### ISSUE THREAD

**Issue by andk** [bluefeet/MooX-BuildArgs#5]
I have a lot of pass reports before Config-MethodProxy-0.02 was uploaded. They were run with 0.01. Maybe Moox-BuildArgs-0.03 was uploaded before Config-MethodProxy-0.02? Whatever. Since 0.02 is available I get fails whatever I try.

Diagnostics:

Can't locate main.pm in @INC (you may need to install the main module) (@INC contains: /tmp/loop_over_bdir-4993-xG5Vt5/MooX-BuildArgs-0.03-0/blib/lib /tmp/loop_over_bdir-4993-xG5Vt5/MooX-BuildArgs-0.03-0/blib/arch /home/sand/src/perl/repoperls/installed-perls/perl/v5.25.3/8942/lib/site_perl/5.25.3/x86_64-linux-ld /home/sand/src/perl/repoperls/installed-perls/perl/v5.25.3/8942/lib/site_perl/5.25.3 /home/sand/src/perl/repoperls/installed-perls/perl/v5.25.3/8942/lib/5.25.3/x86_64-linux-ld /home/sand/src/perl/repoperls/installed-perls/perl/v5.25.3/8942/lib/5.25.3 .) at /home/sand/src/perl/repoperls/installed-perls/perl/v5.25.3/8942/lib/site_perl/5.25.3/Module/Runtime.pm line 317.
t/method_proxy_args.t .. 
Dubious, test returned 2 (wstat 512, 0x200)
No subtests run 

HTH&&Thanks,

**Comment by bluefeet** [comment]
This should be fixed by #6.
